
questions:
  - &cluster_name
    identifier: cluster_name
    question: 'Name of the cluster'

  - &domain
    identifier: domain
    question: 'Fully-qualified domain name for cluster nodes'
    default: '<%= domain.config.cluster %>.cluster.local'

  - &externaldns
    identifier: externaldns
    question: 'External DNS server IP'

  - &internaldns
    identifier: internaldns
    question: "Internal DNS server IP (usually the controller's primary IP)"

  - &root_password
    identifier: root_password
    question: 'Root user encrypted password'

  - &root_ssh_key
    identifier: root_ssh_key
    question: 'Root user SSH key'

  - &dns_type
    identifier: dns_type
    question: 'DNS type to use for cluster'
    default: 'hosts'
    choices:
      - 'hosts'
      - 'named'

  - &genders_host_range
    identifier: genders_host_range
    question: "Genders host range specifier for this group, e.g. 'node01,node[05-08]'"

  - &genders_host_role
    identifier: genders_host_role
    question: 'What are the roles of machines in the group?'
    default: 'compute'
    choices:
      - 'compute'
      - 'service'

  - &genders_all_group
    identifier: genders_all_group
    question: 'Include these nodes in the `all` group?'
    type: 'boolean'

  - &genders_additional_groups
    identifier: genders_additional_groups
    question: "Additional genders groups for this group, e.g. 'storage,rack1'; the group being configured is the primary group"
    default: ''

  - &kickstart_template
    identifier: kickstart_template
    question: 'Kickstart template to use'
    default: 'default'

  - &pxelinux_template
    identifier: pxelinux_template
    question: 'PXELINUX template to use'
    default: 'default'

  - &postfix_relay
    identifier: postfix_relay
    question: 'Postfix relay server for mail (usually the controller)'
    default: 'controller.<%= config.networks.pri.domain %>.<%= config.domain %>'

  # Primary network.
  - &pri_network_interface
    identifier: pri_network_interface
    question: 'Interface for the primary network'
    default: 'eth0'

  # Cloud or metal
  #   This is used to define whether the mgt/bmc network should be setup for the nodes
  - &cloud_or_metal
    identifier: cloud_or_metal
    question: 'Is this cluster in the cloud or on metal?'
    default: 'metal'
    choices:
      - 'cloud'
      - 'metal'

  # Management network.
  - &mgt_network_interface
    identifier: mgt_network_interface
    question: 'Interface for the management network'
    default: 'eth1'

  # BMC network
  - &bmc_network_vlan
    identifier: bmc_network_vlan
    question: 'BMC network VLAN channel ID (if applicable)'
    default: ''

  - &bmc_password
    identifier: bmc_password
    question: 'Password for BMC device over LAN'
    default: 'Pa55Word'

  # InfiniBand network.
  - &ib_network_defined
    identifier: ib_network_defined
    question: 'Setup InfiniBand network?'
    type: 'boolean'

  - &ib_network_interface
    identifier: ib_network_interface
    question: 'Interface for the InfiniBand network'
    default: 'ib0'

  # External network. (for local only)
  - &ext_network_defined
    identifier: ext_network_defined
    question: 'Setup external network?'
    type: 'boolean'

  - &ext_network_domain
    identifier: ext_network_domain
    question: 'Domain for the external network'
    default: 'ext'

  - &ext_network_ip
    identifier: ext_network_ip
    question: 'IP for nodes on the external network'
    default: '10.101.<%= node.group.index %>.<%= node.index %>'

  - &ext_network_ip_node
    identifier: ext_network_ip_node
    question: 'IP for the node (external network)'

  - &ext_network_netmask
    identifier: ext_network_netmask
    question: 'Netmask for the external network'
    default: '255.255.0.0'

  - &ext_network_network
    identifier: ext_network_network
    question: 'Network IP for the external network'
    default: '10.101.0.0'

  - &ext_network_interface
    identifier: ext_network_interface
    question: 'Interface for the external network'
    default: 'eth2'

  - &ext_network_gateway
    identifier: ext_network_gateway
    question: 'Gateway for the external network'

  - &ext_network_short_hostname
    identifier: ext_network_short_hostname
    question: 'Hostname for node EXT'
    default: 'controller.<%= config.networks.ext.domain %>'

domain:
  - *cluster_name
  - *domain
  - *externaldns
  - *internaldns
  - *root_password
  - *root_ssh_key
  - *dns_type
  - *postfix_relay

  - *pri_network_interface

  - <<: *cloud_or_metal
    dependent:
    - *mgt_network_interface
    - *bmc_password
    - *bmc_network_vlan

  - <<: *ib_network_defined
    dependent:
    - *ib_network_interface

group:
  - *genders_host_range
  - *genders_host_role
  - *genders_all_group
  - *genders_additional_groups

  - *kickstart_template
  - *pxelinux_template

  - *pri_network_interface

  - <<: *cloud_or_metal
    dependent:
    - *mgt_network_interface
    - *bmc_password
    - *bmc_network_vlan

  - <<: *ib_network_defined
    dependent:
    - *ib_network_interface

node:
  - *root_password

  - *kickstart_template
  - *pxelinux_template

  - *pri_network_interface

  - <<: *cloud_or_metal
    dependent:
    - *mgt_network_interface
    - *bmc_password
    - *bmc_network_vlan

  - <<: *ib_network_defined
    dependent:
    - *ib_network_interface

local:
  - *pri_network_interface

  - <<: *cloud_or_metal
    dependent:
    - *mgt_network_interface
    - *bmc_password
    - *bmc_network_vlan

  - <<: *ib_network_defined
    dependent:
    - *ib_network_interface

  - <<: *ext_network_defined
    dependent:
    - *ext_network_domain
    - *ext_network_ip_node
    - *ext_network_network
    - *ext_network_netmask
    - *ext_network_interface
    - *ext_network_gateway
    - *ext_network_short_hostname
