questions:

  #
  # Base questions
  #

  - &cluster_name
    identifier: cluster_name
    question: 'Name of the cluster'

  - &domain
    identifier: domain
    question: 'Fully-qualified domain name, usually contains cluster name (e.g. mycluster.local.network)'
    default: '<%= domain.config.cluster %>.cluster.local'

  - &root_password
    identifier: root_password
    question: 'Password to use for root user (generate with `openssl passwd -1`)'

  #
  # Networks
  #

  # Network1
  - &network1_label
    identifier: network1_label
    question: 'Label for network1 (to be used in hostname, if this was "pri" then a node would be called "node01.pri")'
    default: 'pri'

  - &network1_ip
    identifier: network1_ip
    question: 'IP pattern for nodes on network1 to use'
    default: '10.10.<%= node.group.index %>.<%= node.index %>'

  - &network1_netmask
    identifier: network1_netmask
    question: 'Netmask for network1'
    default: '255.255.0.0'

  - &network1_network
    identifier: network1_network
    question: 'IP network for network1'
    default: '10.10.0.0'

  - &network1_gateway
    identifier: network1_gateway
    question: 'IP of gateway for network1'
    default: '10.10.0.1'

  # Network2
  - &network2_defined
    identifier: network2_defined
    question: 'Define a second network?'
    type: boolean

  - &network2_label
    identifier: network2_label
    question: 'Label for network2 (to be used in hostname, if this was "mgt" then a node would be called "node01.mgt")'
    default: 'mgt'

  - &network2_ip
    identifier: network2_ip
    question: 'IP pattern for nodes on network2 to use'
    default: '10.11.<%= node.group.index + 100 %>.<%= node.index %>'

  - &network2_netmask
    identifier: network2_netmask
    question: 'Netmask for network2'
    default: '255.255.0.0'

  - &network2_network
    identifier: network2_network
    question: 'IP network for network2'
    default: '10.11.0.0'

  # Network3
  - &network3_defined
    identifier: network3_defined
    question: 'Define a third network?'
    type: boolean

  - &network3_label
    identifier: network3_label
    question: 'Label for network3 (to be used in hostname, if this was "ib" then a node would be called "node01.ib")'
    default: 'ib'

  - &network3_ip
    identifier: network3_ip
    question: 'IP pattern for nodes on network3 to use'
    default: '10.12.<%= node.group.index %>.<%= node.index %>'

  - &network3_netmask
    identifier: network3_netmask
    question: 'Netmask for network3'
    default: '255.255.0.0'

  - &network3_network
    identifier: network3_network
    question: 'IP network for network3'
    default: '10.12.0.0'

  # External network
  - &external_defined
    identifier: external_defined
    question: 'Will there be an external network connection for this node/group? (usually only the controller/login nodes)'
    type: boolean

  # Group information
  - &genders_host_range
    identifier: genders_host_range
    question: 'List of hosts for the group (in genders format, e.g. "node01,node[05-08]")'

  - &genders_additional_groups
    identifier: genders_additional_groups
    question: 'Additional genders groups for this node/group to appear in (e.g. "compute,rack1")'
    default: ''


domain:
  - *cluster_name
  - *domain
  - *root_password

  - *network1_label
  - *network1_ip
  - *network1_netmask
  - *network1_network
  - *network1_gateway

  - <<: *network2_defined
    dependent:
    - *network2_label
    - *network2_ip
    - *network2_netmask
    - *network2_network
    - <<: *network3_defined
      dependent:
      - *network3_label
      - *network3_ip
      - *network3_netmask
      - *network3_network

group:
  - *genders_host_range
  - *genders_additional_groups

  - *network1_ip
  - *network1_netmask
  - *network1_network
  - *network1_gateway

  - <<: *network2_defined
    dependent:
    - *network2_ip
    - *network2_netmask
    - *network2_network
    - <<: *network3_defined
      dependent:
      - *network3_ip
      - *network3_netmask
      - *network3_network

node:
  - *genders_additional_groups

  - *network1_ip
  - *network1_netmask
  - *network1_network
  - *network1_gateway

  - <<: *network2_defined
    dependent:
    - *network2_ip
    - *network2_netmask
    - *network2_network
    - <<: *network3_defined
      dependent:
      - *network3_ip
      - *network3_netmask
      - *network3_network

local:
  - *genders_additional_groups

  - *network1_ip
  - *network1_netmask
  - *network1_network
  - *network1_gateway

  - <<: *network2_defined
    dependent:
    - *network2_ip
    - *network2_netmask
    - *network2_network
    - <<: *network3_defined
      dependent:
      - *network3_ip
      - *network3_netmask
      - *network3_network
