cluster_name: '<%= answer.cluster_name %>'
domain: '<%= answer.domain %>'
root_password: '<%= answer.root_password %>'

networks:
  network1:
    defined: true
    label:  '<%= answer.network1_label %>'
    short_hostname: '<%= node.name %>.<%= config.networks.network1.label %>'
    hostname: '<%= config.networks.network1.short_hostname %>.<%= config.domain %>' 
    ip: <%= answer.network1_ip %>
    netmask: <%= answer.network1_netmask %>
    network: <%= answer.network1_network %>
    gateway: <%= answer.network1_gateway %>
  network2:
    defined: <%= answer.network2_defined %>
    label:  '<%= answer.network2_label %>'
    short_hostname: '<%= node.name %>.<%= config.networks.network2.label %>'
    hostname: '<%= config.networks.network2.short_hostname %>.<%= config.domain %>' 
    ip: <%= answer.network2_ip %>
    netmask: <%= answer.network2_netmask %>
    network: <%= answer.network2_network %>
  network3:
    defined: <%= answer.network3_defined %>
    label:  '<%= answer.network3_label %>'
    short_hostname: '<%= node.name %>.<%= config.networks.network3.label %>'
    hostname: '<%= config.networks.network3.short_hostname %>.<%= config.domain %>' 
    ip: <%= answer.network3_ip %>
    netmask: <%= answer.network3_netmask %>
    network: <%= answer.network3_network %>
  external:
    defined: <%= answer.external_defined %>
