networks:
  pri:
    defined: true
    ip: 10.10.0.1
    short_hostname: controller.pri
    interface: <%= answer.pri_network_interface %>
  mgt:
    ip: 10.11.100.1
    short_hostname: controller.mgt
    interface: <%= answer.mgt_network_interface %>
  bmc:
    ip: 10.11.0.1
  ib:
    defined: <%= answer.ib_network_defined %>
    ip: 10.12.0.1
    short_hostname: controller.ib
    interface: <%= answer.ib_network_interface %>
  ext:
    defined: <%= answer.ext_network_defined %>
    domain: <%= answer.ext_network_domain %>
    ip: <%= answer.ext_network_ip_node || answer.ext_network_ip_node %>
    network: <%= answer.ext_network_network %>
    netmask: <%= answer.ext_network_netmask %>
    gateway: <%= answer.ext_network_gateway %>
    short_hostname: <%= answer.ext_network_short_hostname %>
    interface: <%= answer.ext_network_interface %>
    firewallpolicy: external
build_method: self
files:
  setup:
    - /var/lib/metalware/repo/files/local/dns.sh
    - /var/lib/metalware/repo/files/local/xinetd.sh
    - /var/lib/metalware/repo/files/local/dhcp.sh
    - /var/lib/metalware/repo/files/local/http.sh
  main:
    - /var/lib/metalware/repo/files/local/main.sh
  core:
    - /var/lib/metalware/repo/files/core/base.sh
    - /var/lib/metalware/repo/files/core/chrony.sh
    - /var/lib/metalware/repo/files/core/configs/chrony.conf
    - /var/lib/metalware/repo/files/core/firstrun_scripts/chronyfix.bash
    - /var/lib/metalware/repo/files/core/syslog.sh
    - /var/lib/metalware/repo/files/core/configs/metalware.conf
    - /var/lib/metalware/repo/files/core/configs/rsyslog-remote
    - /var/lib/metalware/repo/files/core/firstrun_scripts/firewall_rsyslog.bash
    - /var/lib/metalware/repo/files/core/postfix.sh
    - /var/lib/metalware/repo/files/core/network-base.sh
    - /var/lib/metalware/repo/files/core/network-ipmi.sh
    - /var/lib/metalware/repo/files/core/network-join.sh
    - /var/lib/metalware/repo/files/core/networking.sh
    - /var/lib/metalware/repo/files/core/configs/authorized_keys
    - /var/lib/metalware/repo/files/local/extra.sh
    - /var/lib/metalware/repo/files/core/configs/dhcpd.conf
    - /var/lib/metalware/repo/files/core/configs/pxelinux_default
    - /var/lib/metalware/repo/files/core/configs/named.conf
    - /var/lib/metalware/repo/files/core/configs/http/deployment.conf
    - /var/lib/metalware/repo/files/core/configs/http/installer.conf
    - /var/lib/metalware/repo/files/core/configs/kscomplete.php
    - /var/lib/metalware/repo/files/core/firstrun_scripts/firewall_main.bash
build:
  pxeboot_path: /var/lib/tftpboot/boot
ntp:
  is_server: true
rsyslog:
  is_server: true
